"""empty message

Revision ID: 28a75346eff0
Revises: 5529b8812450
Create Date: 2024-06-02 13:47:12.217837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28a75346eff0'
down_revision = '5529b8812450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('back_time', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('cost', sa.Integer(), nullable=False))
    op.drop_column('order', 'lease_duration')
    op.drop_column('order', 'imputed_rent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('imputed_rent', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('lease_duration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('order', 'cost')
    op.drop_column('order', 'back_time')
    # ### end Alembic commands ###
