"""empty message

Revision ID: 3bfe56d16f60
Revises: 7f4781c0ef87
Create Date: 2024-06-03 14:36:17.262256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bfe56d16f60'
down_revision = '7f4781c0ef87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('car_collect_list', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'car_collect_list')
    # ### end Alembic commands ###
