"""empty message

Revision ID: 5529b8812450
Revises: d15237421575
Create Date: 2024-06-02 09:30:23.474888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5529b8812450'
down_revision = 'd15237421575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'status')
    # ### end Alembic commands ###
